#+TITLE: TwinCat 3 Asennus ja käyttöönotto
#+STARTUP: showall
* Mikä TwinCat?
TwinCat (The Windows Control and Automation Technology) on Beckhoffin
automaatiojärjestelmien ydin.

Se on PC-pohjainen ohjelmisto, joka muuttaa minkä tahansaPC:n tehokkaaksi automaatiojärjestelmien ohjaimeksi.

TwinCat 3 on ohjelmiston uusin versio, jonka avulla automaatiohjelmointia
voidaan tehdä IEC 61131-3 standardin mukaisten kielten lisäksi C ja C++
ohjelmointikielillä. Twincat 3 on rakennettu Microsoftin Visual Studio
ohjelmointiympäristön päälle.
* Asennus ja ensimmäinen käynnistys
** Vaatimukset
*** Windows XP tai uudempi
*** CPU 1.6Ghz
*** 2GB RAM
*** 3GB kiintolevytilaa
** Lisenssi
TwinCat 3 lisenssi on täysin ilmainen mutta sen lisenssi on luotava uudelleen 7
päivän välein.
** Virtuaalikoneet
Koska TwinCat ajaa PLC emulaatiota PC:llä saattaa se aiheuttaa ongelmia,
jos samaan aikaan on käytössä muita virtuaalikoineita. TwinCat projektia ei
esimerkiksi pysty asettamaan Run-moodiin, jos samaan aikaan PC:llä on käynnissä VirtualBox.
** Core isolation
TwinCat projekti
* PLC projektin
** Asetukset
** PLC projekti
*** Ohjelmointitavat
** Globaalit muuttujat
** Projektin ajaminen TwinCat runtimella
** Ohjelman debuggaus ajon aikana
** I/O mäppäys
*** EtherCat laitteiden lisääminen
*** Terminaalimoduulien lisääminen
* HMI käyttöliittymä
** Eri toteutustavat
** Web toteutuksen vaiheet
** UI mäppäys muuttujiin
* Etäyhteys koulun laitteistoon

|-----+---------------+-------|
| CPU | Arkkitehtuuri | Muuta |
|-----+---------------+-------|
| Häh | Jotain        | Ehkä  |
|     |               |       |
|     |               |       |

* Lähteet
** https://download.beckhoff.com/download/document/catalog/TwinCAT_3_Booklet.pdf
